create table IF NOT EXISTS produkt (id bigint generated by default as identity (start with 1), cena double, nazwa varchar(255), vege boolean, primary key (id))
create table IF NOT EXISTS zamowienie (id bigint generated by default as identity (start with 1), datazam varchar(255), wynos boolean, primary key (id))
create table IF NOT EXISTS zamprod (id integer generated by default as identity (start with 1), ilosc integer, prod bigint, zam bigint, primary key (id))
alter table zamprod add constraint if not exists FKk970uei1j9f0is0r9yogaihy4 foreign key (prod) references produkt
alter table zamprod add constraint if not exists FKdur5krg1ic6sbeaaf4knmobuk foreign key (zam) references zamowienie
